### ISSUE TITLE
Can only edit widget?!

### ISSUE THREAD

**Issue by tcm692** [godaddy/wp-contact-widgets#16]
I had the widget set up & working perfectly, until I changed themes on our godaddy hosted wp site. Changed site & contact info disappeared.  When looking at the plugins -> Contact Widget, the only options I have are 'deactivate' or 'edit'. When I click 'edit', I'm directed to the page that allows me to edit the plugin, NOT edit the information.

Yikes!!

![capture](https://cloud.githubusercontent.com/assets/3605358/17072433/d0d1d144-502d-11e6-89b7-eba8624f2760.PNG)

How do I change that back??!!

**Comment by jonathanbardo** [comment]
Hey @tcm692!

It's entirely possible that some widgets disappear when changing themes with WordPress. You can add them back to a sidebar using the customizer or the widgets admin menu (yousite.com/wp-admin/widgets.php).

The widgets are called "Social Profiles" and "Contact Details" and will only be available when the contact widgets plugin is activated. 

Let me know if that works for you.

**Comment by fjarrett** [comment]
Widgets go to the "Inactive Widgets" area when switching to a theme that uses different sidebar names. It's expected behavior in WordPress.
