### ISSUE TITLE
Unable to edit email address

### ISSUE THREAD

**Issue by ignomegee** [godaddy/wp-contact-widgets#18]
hi, I have changed my business email but am unable to edit the contact widget - doesn't complete the save process. Cheers.

**Comment by jonathanbardo** [comment]
Hey @ignomegee,

Can you take a screenshot of the widget before saving. It would help us figure out why you are seeing this issue. 

Thanks

**Comment by ignomegee** [comment]
Hi Jonathan,

here is a screenshot of the widget as it now is. I try to change the email
address to info@papyrusprintingpress.com.au but it doesn't save.

Cheers,
Andrea

**Comment by jonathanbardo** [comment]
@ignomegee I've tried locally with the email address you provided and everything seems to be working as expected with the latest version of this plugin. 

I think you need to upload a screenshot directly on Github. As of right now, I still can't see anything.

**Comment by ignomegee** [comment]
<img width="424" alt="screen shot 2016-09-05 at 8 00 13 am" src="https://cloud.githubusercontent.com/assets/21700584/18293179/8c630548-74d4-11e6-8352-cfee319cb185.png">

**Comment by fjarrett** [comment]
@ignomegee It looks like there are other plugins installed that are adding custom fields to your widgets. Can you provide us with a list of all plugins active on your site?
