### ISSUE TITLE
Safari Contact Widgets

### ISSUE THREAD

**Issue by pascalro** [godaddy/wp-contact-widgets#19]
Hello, I have issue on Safari and Mac OS Sierra GM, the field verification is broken by strange message and behaviour. Thanks for your support.
![screen shot 2016-09-17 at 04 12 49](https://cloud.githubusercontent.com/assets/4346641/18605263/358ea89c-7c8d-11e6-8c14-08c7062454fd.png)

**Comment by jonathanbardo** [comment]
Hey @pascalro,

I don't see the any of the widgets from the contact widgets plugin in the screenshot you provided. We don't have any verification field so I'm not really sure I understand your issue.

**Comment by pascalro** [comment]
Hello, sorry you are right, I'm wrong on the name widget, it’s not yours extension. But thanks for your answer and sorry again. We use wp contact widgets on http://luxuryrentingsuisse.com 
Sheers
Pascal
