### ISSUE TITLE
"contact-widgets/includes/social-networks.php (inactive)" - What does this mean 

### ISSUE THREAD

**Issue by thepentatonic** [godaddy/wp-contact-widgets#20]
The plugin itself is activated but this part of the plugin seems to be inactive. 

Attached is an image... 
<img width="1280" alt="screen shot 2016-12-03 at 13 57 15" src="https://cloud.githubusercontent.com/assets/24355928/20859950/de36517a-b964-11e6-89ae-2dd65f31341a.png">

Thank you

**Comment by fjarrett** [comment]
Hi thepentatonic,

This area of WordPress is where you can edit files on the server, the "inactive" word here is not referring to the status of the plugin, but the file you are editing.

You should exercise extreme caution when using the File Editor. You can learn more here: https://codex.wordpress.org/Editing_Files

From your screenshot, I see you are editing the `$fields` array, which I advise against. The next time you update the plugin, these changes will be lost. Also, if you make a mistake in your syntax, your site could easily through a fatal error and lock you out.

Instead, you can simply drag-and-drop the widget into a Sidebar area, and update the fields with your links as seen in these screenshots: https://wordpress.org/plugins/contact-widgets/screenshots/

If you have questions in the future about the plugin, please visit the [WordPress.org support forum](https://wordpress.org/support/plugin/contact-widgets) where we will be happy to help!
