### ISSUE TITLE
Contact plugin not showing up to inlude in posts/pages

### ISSUE THREAD

**Issue by hallidayny** [godaddy/wp-contact-widgets#23]
Hi - I have downloaded and activated the plugin. I cannot tell my PHP version since it is a Managed Hosting plan. I have put thru request of hosting provider to upgrade to latest PHP release. What else can I do to begin using the plugin? thanks.

**Comment by jonathanbardo** [comment]
@hallidayny This plugins requires php 5.4 which most Managed WordPress host should have already. Is it not working for you?
