### ISSUE TITLE
Contact Widgets Video

### ISSUE THREAD

**Issue by nicksavov** [godaddy/wp-contact-widgets#25]
Hi Contact Widgets Maintainers,

We just published a big WordPress Beginner class, that's available for free on YouTube (sponsored by GoDaddy).

One of the lessons demonstrates installing and using Contact Widgets:
https://www.youtube.com/watch?v=Y3NsrWHd_us

It would be great if you guys would embed it somewhere in your documentation. It's an excellent introduction to Contact Widgets.

Our Drupal class has about 900,000 views on YouTube so far. Hopefully the WordPress class will catch up to it soon and get Contact Widgets some exposure in the process.

Let us know if you have any questions and we'll be glad to answer.

Thanks,
Nick

**Comment by fjarrett** [comment]
Great video! It shall be done!
