### ISSUE TITLE
Adding additional fields

### ISSUE THREAD

**Issue by jmcfeely** [godaddy/wp-contact-widgets#28]
Hi there,

I am looking to add a field to my contact form that will display the registered business number for the company but I am unsure as to how to add it. I can see from the read me that I can add fields but I am unsure as to where I can add the field it says I need to add the following:

<pre lang="php">
add_filter( 'wpcw_widget_contact_custom_fields', function( $fields, $instance ) {

  $fields['cellphone'] = [
    'order'       => 2,
    'label'       => __( 'Cellphone:', 'YOURTEXTDOMAIN' ),
    'type'        => 'text',
    'description' => __( 'A cellphone number that website vistors can call if they have questions.', 'YOURTEXTDOMAIN' ),
  ];

  return $fields;

}, 10, 2 );
</pre>

**Comment by EvanHerman** [comment]
Hi @jmcfeely ,

You'll want to add that example code to your themes **functions.php** file, or into an mu-plugin or custom plugin.

If you are using a child theme, it's safe to place inside of functions.php. If you are uncomfortable editing .php files, you can use a third party plugin to add code snippets to your site.

One that seems to work well is [My Custom Functions](https://wordpress.org/plugins/my-custom-functions/) which can be downloaded from the WordPress.org plugin directory.

Once you add the snippet, you should see the new 'Cellphone' field added to the contact widget.

**Example:**
![Example](https://cldup.com/frDLLyvUXu.png)

Let us know if that helps out at all.


Evan
