### ISSUE TITLE
Bug with WP 4.8.1 

### ISSUE THREAD

**Issue by JonBravo** [godaddy/wp-contact-widgets#45]
The widget is causing a strange output and errors using the new version of WP.

In the title area, I try to type "Social", and it will not save it.  It changes the word to "Array" and then this error is displayed in the widget area:

Warning: preg_match_all() expects parameter 2 to be string, array given in /home/viqiacom/public_html/pickyclickyuat.com/wp-includes/formatting.php on line 219

Warning: array_intersect(): Argument #2 is not an array in /home/viqiacom/public_html/pickyclickyuat.com/wp-includes/formatting.php on line 220

Warning: preg_split() expects parameter 2 to be string, array given in /home/viqiacom/public_html/pickyclickyuat.com/wp-includes/formatting.php on line 225

Warning: Invalid argument supplied for foreach() in /home/viqiacom/public_html/pickyclickyuat.com/wp-includes/formatting.php on line 227

Warning: implode(): Invalid arguments passed in /home/viqiacom/public_html/pickyclickyuat.com/wp-includes/formatting.php on line 289

I have not done anything except update WP to 4.8.1.

**Comment by fjarrett** [comment]
Thanks for the report @JonBravo. I'm not able to reproduce this on a vanilla 4.8.1 install.

Can you please provide us with a list of your active plugins, their version, and which theme you are using? Thank you.

**Comment by JonBravo** [comment]
Addons for Visual Composer v1.6
All In One SEO Pack v2.3.14.2
Contact Widgets v1.4.1
Duplicate Post v3.2
Envato WordPress Toolkit v1.7.3
GTranslate v2.8.25
HTML5 Responsive FAQ v2.5.3
Knowledge Base for Documents and FAQs v3.1.2
Limit Login Attempts v1.7.1
Ninja Forms v3.1.8
Slider Revolution v5.4.5.1
Ultimate Addons for Visual Composer v3.16.14
Under Construction v2.35
UpdraftPlus - Backup/Restore v2.13.4.21
WP Support Plus v.8.0.7
WPBakery Visual Composer v5.2

THEME: Stockholm by Select Themes V4.1

**Comment by EvanHerman** [comment]
Hi @JonBravo 

Let me do some additional digging. I'll try and setup a test instance on 4.8 and do an upgrade from 4.8.1 to see if anything weird is going on. I will report back here when I have some additional info for you.

**Comment by fjarrett** [comment]
@EvanHerman I did the same and could not replicate the problem.

@JonBravo Please try deactivating those other plugins one-at-a-time (but keep Contact Widgets active) to try to isolate if any of them are the root cause.

**Comment by JonBravo** [comment]
I have deactivated one by one, and the problem still persists.

**Comment by fjarrett** [comment]
Thanks @JonBravo - are you experiencing the issue with this theme only, or with others too?

**Comment by JonBravo** [comment]
Yes, it seems to be just this theme.  Any ideas??

**Comment by fjarrett** [comment]
@JonBravo It's likely due to an error in the way that theme implemented the widget area. Your best course of action will be to reach out to the theme author.

**Comment by JonBravo** [comment]
Yes, the downgrade of my theme has corrected the problem.  Thanks for the effort and support!
