### ISSUE TITLE
Title not saving

### ISSUE THREAD

**Issue by raddrives** [godaddy/wp-contact-widgets#50]
Not sure what is up but title will not save. It keeps reverting back to Array and nothing for title displays. Was working while back but now nope. see raddrives.com

**Comment by EvanHerman** [comment]
Sorry for the delay in responding here. I did some testing and I am not able to replicate the issue. If you are still encountering some issues, feel free to post back here with steps to reproduce and I can jump in and help out.

My best guess is that there was some sort of conflict with another plugin that you have installed.
