### ISSUE TITLE
Pluggin interferes with WordPress Screener Plus Theme

### ISSUE THREAD

**Issue by AntStaffSpeaks** [godaddy/wp-contact-widgets#54]
Hi,

Recently (after there have been no issues for over a year), I noticed after troubleshooting, that the Contact Widgets (from GoDaddy) no longer works properly with my Screener Plus theme.  For some reason when the plugin is activated, it turns various icons that are located throughout my pages (Facebook, instagram, twitter, and others) into a flashing question mark / exclamation point - where it is not able to recognize the icon.  After speaking to Screener Plus (famed themes), and discovering which plugging caused the issue, here was there response:

David repliedJun 8, 16:00 "Hi Anthony,I recommend you try to use a different plugin. Because this plugin auto converts all FontAwesome icon to SVG type. That is why the icon does not appear properly.Or you can submit the issue to plugin's author to ask for help."  I would like to use this plugin again so i can display my address, additional social media icons etc in  my sidebar and footer.

**Comment by LoganStrike** [comment]
I'm having the same issue. There are many WordPress themes and plugins that use older versions of Font Awesome, so when Font Awesome 5 attempts to replace all the icons with inline SVG, any old icons that are not compatible with Font Awesome 5 are replaced with the blinking "missing icon" icon.

The workaround I've found is to disable the "missing icon" feature of Font Awesome 5. This seems to allow the older Font Awesome icons to still be visible alongside the new icons.

`<script>
window.FontAwesomeConfig = { showMissingIcons: false }
</script>
`

**Comment by AntStaffSpeaks** [comment]
Hi,

Where can I find this in the coding (I’m a complete novice) to make this update??

Kindest regards,


Anthony C. Stafford
Empowerment Coach | Global Speaker | Life Strategist | Mentor

(818) 962-0191
AntStaffSpeaks@gmail.com
Anthony@antstaffspeaks.com
www.antstaffspeaks.com
YouTube Channel: AntStaffSpeaks 

"Transform Your Life with Passion & Purpose!"

**Comment by EvanHerman** [comment]
@AntStaffSpeaks Thank you for taking the time to report that here. I am working on patching this up and getting a new release out to WordPress.org that should resolve the issue for you.

I have a [pull request merged](https://github.com/godaddy/wp-contact-widgets/pull/55) into our `develop` branch for testing which will get merged into the `master` branch and rolled out to WordPress.org for everyone to make use of.

I will post back here when I've rolled things out to WordPress.org

**Comment by EvanHerman** [comment]
This should now be resolved in Contact Widgets v1.5.1 which has been released on WordPress.org. Let us know if you are still encountering issues after the update. Have a great day, and thank you again for reporting the issue here!
