### ISSUE TITLE
Installation failed: Destination folder already exists.

### ISSUE THREAD

**Issue by WMB679** [godaddy/wp-contact-widgets#63]
I want to reinstall the wp-contact-widget but it seems an old folder exists. Please can you advise how to resolve this issue.

Many thanks

**Comment by EvanHerman** [comment]
Hi @WMB679 

Sounds like you may need to manually delete the plugin file via FTP. I would FTP into the server and remove the contact-widgets plugin, and then re-download the plugin from the WordPress.org repository from your WordPress dashboard.
