### ISSUE TITLE
Mobile phone details

### ISSUE THREAD

**Issue by pierreroodman** [godaddy/wp-contact-widgets#68]
Could you please add a field to add a mobile number.

**Comment by EvanHerman** [comment]
@pierreroodman This plugin is for social media contact details and was not designed for things like phone numbers. If you'd like to add a widget to your site with a phone number you can use the contact block widget, which would allow you to add your email, phone number, fax or address with a Google Map.

If you need an icon added to the social media widget for phone numbers, you can do so by defining your own custom field. We have some helpful documentation in the plugins readme outlining the process here on Github https://github.com/godaddy/wp-contact-widgets#how-do-i-add-additional-fields-to-the-social-media-profiles-widget

**Comment by pierreroodman** [comment]
Thank you for your response. I will take a look at the link you shared with
me.

Regards
Pierre
