### ISSUE TITLE
Social Media Icons not Appearing

### ISSUE THREAD

**Issue by pbuerk** [godaddy/wp-contact-widgets#70]
The social media icons in my Footer is not displaying the icons but rather it is showing just a square for each of them. It was working perfectly fine before, and I do not think I made any updates to other plugins that would have caused this. Any suggestions on how to fix this? See screenshot below.
<img width="1032" alt="Social Icon Issue" src="https://user-images.githubusercontent.com/35703582/55799714-0b28c800-5aa0-11e9-98d3-8c595bfcffd5.png">

**Comment by EvanHerman** [comment]
@pbuerk Do you have a link to the site in question? This is most likely a collision with another theme or plugin you have that is also loading a different version of Font Awesome.

**Comment by pbuerk** [comment]
@EvanHerman Yes, I figured it is something like that but cannot seem to find out what theme that may be. I have not added any new ones that resulted in it to stop working. This link is the following:

https://www.scramblersrestaurants.com

**Comment by EvanHerman** [comment]
@pbuerk Ah, yes that would do it. No problem at all - glad that it wasn't something larger at play. Hope you have a great week!

**Comment by suzyvee** [comment]
eva how did you change the beaver builder to FA5?

**Comment by EvanHerman** [comment]
@suzyvee You can find some instructions in the Beaver Builder documentation here: https://kb.wpbeaverbuilder.com/article/732-add-font-awesome-5-pro-icons

> Add a filter to load FA 5 Pro from a URL
> If you have downloaded the Font Awesome 5 Pro icon set and unzipped it onto a server, you can add a filter to point to the server URL and path.
> 
> In your child theme, open functions.php for editing.
> Append the following line to the file:
```php
add_filter( 'fl_get_fa5_url', function() { return 'HTTP://EXAMPLE.COM/PATH/all.css'; } );
```
> 
> Replace HTTP://EXAMPLE.COM with the URL for your server, and replace PATH with the path to the all.css file in the Font Awesome 5 Pro folder.
> Save the file.

**Comment by suzyvee** [comment]
what if I don't have a pro account?
