### ISSUE TITLE
Icons disappeared

### ISSUE THREAD

**Issue by rafdarrow** [godaddy/wp-contact-widgets#71]
After the most recent WP update GoDaddy made on Oct 17 to my site ([transformshorecrest.org](http://transformshorecrest.org)), the social icons in the footer using this widget have disappeared. Only squares are showing. I update the plugin. I deactivated and reactivated the plugin. I tested on Chrome, Firefox and iPhone X.

**Comment by EvanHerman** [comment]
It looks like your theme or another plugin is also loading an older version of Font Awesome. You can force our plugin to use the old version of Font Awesome by doing the following:

```css
.wpcw-widgets .fa {
   font-family: FontAwesome;
}
```

You can add that to the customizer 'Additional CSS' section. You can get there from the dashboard by going to 'Appearance > Customizer' scroll down to Additional CSS and then drop the code above in there.

Let us know if that helps 👌

**Comment by rafdarrow** [comment]
It worked!
Thank you,

Raffi

*--*
Raffi Darrow
*Web Developer and Communications Manager*
[image: Shorecrest Preparatory School] <https://www.shorecrest.org/>
*Shorecrest Preparatory School*
5101 First Street Northeast | St. Petersburg, FL 33703
727-522-2111 x 213 | phone
727-466-1213 | direct dial
727-688-3968 | mobile
website <https://www.shorecrest.org/> | blog <http://blog.shorecrest.org/> |
 vCard
<http://www.dynasend.com/signatures/vcard/rdarrow-at-shorecrest.org.vcf> |
map
<https://www.google.com/maps/place/5101+1st+St+NE,+St.+Petersburg,+FL+33703/@27.8195281,-82.6434387,14.45z/data=!4m5!3m4!1s0x88c2e14c821db0a1:0x6c044f454f10c095!8m2!3d27.8190237!4d-82.6339709>
[image: Facebook] <https://www.facebook.com/ShorecrestPrep>[image: Twitter]
<http://twitter.com/shorecrest>[image: Instagram]
<https://www.instagram.com/shorecrestprep/>[image: YouTube]
<https://www.youtube.com/channel/UCjCgtNCGTpfd0G2JeyPo4BA>[image: Flickr]
<https://www.flickr.com/photos/shorecrest/sets/>[image: Pinterest]
<https://www.pinterest.com/shorecrestprep/boards/>[image: LinkedIn]
<http://www.linkedin.com/in/rafdarrow/>[image: Donate]
<https://forms.diamondmindinc.com/shorecrest/online_giving>
An Apple Distinguished School
