### ISSUE TITLE
Plugin not working with WordPress 5.3

### ISSUE THREAD

**Issue by ruiengana** [godaddy/wp-contact-widgets#73]
Hi,

I am getting a error when using trying to use this plugin in WordPress 5.3.

My theme uses this plugin, but when I edit the page to setup, every time I click in the block browser gives me an error saying "The editor has encountered an unexpected error."
Attempt Recovery
Copy Post Text

Can you help?

Thank you!
Rui

**Comment by EvanHerman** [comment]
Hi @ruiengana 

Thank you for reporting this. We are working on a patch right now that will get this resolved. We should have a fix out to the WordPress.org repository shortly.

**Comment by ruiengana** [comment]
That's excellent. Thank you so much.
