### ISSUE TITLE
Edit existing information

### ISSUE THREAD

**Issue by ejonesthorne** [godaddy/wp-contact-widgets#9]
Some of the information I entered into the plugin when I established my Wordpress/GoDaddy accounts is incorrect; however, I am unable to figure out how to edit this information.

**Comment by fjarrett** [comment]
@ejonesthorne These are widgets, they can be edited under Appearance > Widgets in the WordPress Admin area.

https://wordpress.org/plugins/contact-widgets/screenshots/

In the future you can use the [WordPress.org Support Forum](https://wordpress.org/support/plugin/contact-widgets) for help, this issue board is for reporting bugs. Thanks!
